#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
	/* QUESTION : Find the digit number of a positive number randomly generated by the user. */

	//SOLUTION :
	int num;
	srand(time(NULL));
	num = rand() % 100000;
	printf("Random Number:%d\n", num);

	if (num < 10)
	{
		printf("Number is single digit\n");
	}
	else if (num < 100)
	{
		printf("The number is two digits\n");
	}
	else if (num < 1000)
	{
		printf("The number is three digits\n");
	}
	else if (num < 10000)
	{
		printf("The number is four digits\n");
	}
	else if (num < 100000)
	{
		printf("The number is five digits\n");
	}
	else
	{
		printf("The number is six digits\n");
	}
}
